In [55]:
from astropy.io import fits
from astropy.table import Table

import pandas as pd
import numpy as np

In [2]:
folder = 'C:/Users/oryan/Documents/esac-project/data'

In [7]:
with fits.open(f'{folder}/MPA-JHU_full_catalogue.fits') as hdul:
    header = hdul[1].header
    data = hdul[1].data
hdul.close()

In [66]:
mask = (data['RA'] > 316) & (data['RA'] < 317) & (data['DEC'] > 10) & (data['DEC'] < 10.5)

In [67]:
data[mask]['RA']

array([316.523  , 316.88214, 316.74976, 316.7563 , 316.86942, 316.51587,
       316.78067, 316.73346, 316.3973 , 316.49448, 316.22794, 316.17392,
       316.0764 , 316.00565, 316.0102 , 316.0642 , 316.12677, 316.1075 ,
       316.18677, 316.08704, 316.11215, 316.08923, 316.2042 , 316.1101 ,
       316.0165 , 316.01883, 316.35858, 316.33823, 316.32065, 316.29303,
       316.23743, 316.22806, 316.6417 , 316.69238, 316.67194, 316.7144 ,
       316.5011 , 316.6712 , 316.5416 , 316.6465 , 316.60916, 316.88327,
       316.84695, 316.8421 , 316.95645, 316.92627, 316.8748 , 316.5099 ,
       316.64877, 316.93533, 316.82587, 316.99216, 316.60226, 316.71823],
      dtype=float32)

In [68]:
data[mask]['DEC']

array([10.03544 , 10.089563, 10.119172, 10.08044 , 10.031913, 10.074603,
       10.112399, 10.079175, 10.023276, 10.010626, 10.054752, 10.035668,
       10.080715, 10.079584, 10.051458, 10.394751, 10.388082, 10.436171,
       10.339944, 10.177538, 10.303833, 10.344913, 10.234186, 10.277639,
       10.220407, 10.414286, 10.14388 , 10.263415, 10.209079, 10.206338,
       10.237064, 10.464688, 10.414721, 10.457731, 10.263753, 10.267384,
       10.273966, 10.280714, 10.345424, 10.480538, 10.423377, 10.234004,
       10.249486, 10.341285, 10.497589, 10.436571, 10.494396, 10.072271,
       10.294031, 10.0657  , 10.156096, 10.303626, 10.323047, 10.098798],
      dtype=float32)

In [74]:
data[mask]['Z']

array([ 1.0426832e-04, -1.8284548e-04,  1.3754113e-01,  1.4654855e-01,
        9.8882526e-02,  1.6243844e-01,  9.8390356e-02,  9.8643124e-02,
        6.4636379e-01,  1.5778106e-04, -4.8807339e-04,  1.5103300e-01,
        4.4718623e-01,  2.2235464e-01,  2.2366546e-01, -2.6763117e-04,
        4.1532540e-03, -5.5208984e-05, -1.1916948e-05, -1.1020384e-04,
       -1.0742157e-04,  1.4789166e-01,  2.1111085e-01,  4.1415337e-01,
       -4.0487259e-05,  1.0770077e-01, -4.5604131e-04, -1.2241969e-04,
        7.1808338e-02,  8.6521603e-02,  3.8837519e-01,  1.5737154e-01,
        3.2818970e-01,  3.2259181e-01,  9.8369144e-02,  9.7541720e-02,
       -1.8675008e-04,  9.8445408e-02,  1.7161120e-02,  4.0376140e-03,
        9.6457377e-02, -4.5879860e-05, -7.9598965e-04,  9.8668192e-05,
       -7.8646954e-05, -9.0718808e-05,  1.3503782e-04,  1.6253935e-01,
        1.3748106e-01, -3.5854633e-04,  1.3925503e-01, -4.8121638e-05,
        1.7637073e-01,  2.3027702e-01], dtype=float32)

In [71]:
data.columns

ColDefs(
    name = 'SPECOBJID_1'; format = '19A'
    name = 'PLATEID_1'; format = 'J'
    name = 'MJD_1'; format = 'J'
    name = 'FIBERID_1'; format = 'J'
    name = 'BPTCLASS'; format = 'I'
    name = 'LGM_TOT_P2P5'; format = 'E'
    name = 'LGM_TOT_P16'; format = 'E'
    name = 'LGM_TOT_P50'; format = 'E'
    name = 'LGM_TOT_P84'; format = 'E'
    name = 'LGM_TOT_P97P5'; format = 'E'
    name = 'LGM_FIB_P2P5'; format = 'E'
    name = 'LGM_FIB_P16'; format = 'E'
    name = 'LGM_FIB_P50'; format = 'E'
    name = 'LGM_FIB_P84'; format = 'E'
    name = 'LGM_FIB_P97P5'; format = 'E'
    name = 'OH_P2P5'; format = 'E'
    name = 'OH_P16'; format = 'E'
    name = 'OH_P50'; format = 'E'
    name = 'OH_P84'; format = 'E'
    name = 'OH_P97P5'; format = 'E'
    name = 'OH_ENTROPY'; format = 'E'
    name = 'SFR_TOT_P2P5'; format = 'E'
    name = 'SFR_TOT_P16'; format = 'E'
    name = 'SFR_TOT_P50'; format = 'E'
    name = 'SFR_TOT_P84'; format = 'E'
    name = 'SFR_TOT_P97P5'; format = 'E'
  